version: '3.8'

services:
  mysql:
    build:
      context: ./mysql  # Path to the MySQL directory
      dockerfile: Dockerfile-mysql  # MySQL Dockerfile
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
    - ./my.cnf:/etc/mysql/my.cnf

  python-app:
    build:
      context: ./python_scripts  # Path to the Python application directory
      dockerfile: Dockerfile-python  # Python Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - my_network
    depends_on:
      - mysql

networks:
  my_network:
    driver: bridge
