# Use the official Python image
FROM python:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Python scripts and requirements file into the container
COPY requirements.txt .
COPY CreateDB.py .
COPY CreateTables.py .
COPY ETL.py .
COPY ExampleQueries_fromLocalURI.py .

# Install required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables to connect to MySQL (optional)
ENV MYSQL_HOST="mysql"
ENV MYSQL_PORT=3306
ENV MYSQL_USER="user_1"
ENV MYSQL_PASSWORD="user_1_Sopas_de_aj8!"
ENV MYSQL_DATABASE="Mira_Transfermarkt"

# run sequentially python scripts
CMD ["sh", "-c", "python CreateDB.py && python CreateTables.py && python ETL.py && tail -f /dev/null"]
